### ISSUE TITLE
Docker image is completely flat

### ISSUE THREAD

**Issue by fatalbanana** [rspamd/rspamd-docker#6]
Rather we should be layered on top of `debian:bookworm-slim` or whichever applicable base image. But we want to shed packages...  `RUN --mount=type=cache,from=...` looks like a likely solution but CI is confirmed not ready for this (drone docker in docker version is 20.10).

**Comment by polarathene** [comment]
`20.10` point release could support it with the syntax hint at the top of the `Dockerfile`. In [this comment](https://github.com/rspamd/rspamd-docker/pull/5#discussion_r1344176472) you referred to the version of Docker as 2020, not sure if you are using a very early release of `20.10` or newer one that can use `DOCKER_BUILDKIT=1`.

Is it necessary to use Drone? Github Actions are well suited for this and I'm happy to explain the ones used for `docker-mailserver` if you're interested in adopting something similar.

**Comment by polarathene** [comment]
For additional reference, since you were not able to adopt `RUN --mount=type=bind` to avoid a `COPY` you don't need to persist, when you are able to leverage this, I [provided a snippet here](https://github.com/rspamd/rspamd-docker/pull/5#discussion_r1344020721) which you could also throw in `--mount=type=cache` for `apt` to use (_both mount types can be used with the single `RUN`_).

For your Drone systems this may be a non-issue, but on ephemeral CI runners like Github Actions where the environment is reset each run, cache from CI runs is persisted remotely. Docker `buildx` can export the build image layers as cache, but cache mounts are a different kind, they need additional handling to restore for future use.

On local dev systems where that's a non-issue, the cache mount is convenient as the data is not lost to invalidated layers. You can alternatively use it without persistence to keep data out of the image, but then the tmpfs mount is probably more suitable.
